"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    _fallback_key = os.getenv("DJANGO_SECRET_KEY", "")
    _is_test = "test" in sys.argv or "pytest" in sys.modules
    if _is_test:
        SECRET_KEY = _fallback_key
    else:
        _debug_env = os.getenv("DJANGO_DEBUG", "false").lower() == "true"
        if _debug_env:
            SECRET_KEY = _fallback_key
        else:
            sys.exit("🔴 DJANGO_SECRET_KEY 환경변수가 설정되어 있지 않습니다. 서버를 시작할 수 없습니다.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

if not DEBUG:
    _allowed = os.getenv('ALLOWED_HOSTS', '').strip()
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] or ['localhost']
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'core',
    'user',
    'recipes',
    'community',
    'fridges',
    'shopping',
    'chatbots',
    'drf_spectacular',  # 문서화
    'drf_spectacular_sidecar',  # UI용
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:40001",
    "http://localhost:3000",
    "https://frontend-domain.com",
    "https://recipeyo.duckdns.org",
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

"""
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}
"""

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        #'rest_framework_simplejwt.authentication.JWTAuthentication',
        'user.authentication.RedisJWTAuthentication',  # 인증 클래스
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # 기본 인증
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # 문서화
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler', # 전체 커스텀 예외 처리기
    'DEFAULT_THROTTLE_CLASSES': [
        'common.throttles.AnonBurstRateThrottle',
        'common.throttles.AnonDayRateThrottle',
        'common.throttles.UserBurstRateThrottle',
        'common.throttles.UserDayRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon_burst': '30/min',
        'anon_day': '1000/day',
        'user_burst': '120/min',
        'user_day': '10000/day',
        # 유튜브 레시피 임포트 (common.throttles.YouTubeImport*)
        'youtube_import_day': '50/day',
        'youtube_import_burst': '3/min',
        'youtube_import_poll': '120/min',
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Backend Core API',
    'DESCRIPTION': '백엔드 아키텍처 API 문서',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',  # CDN 없이 자체 서버에서 UI 실행
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SCHEMA_PATH_PREFIX': r'/api/v1/',

    'COMPONENT_SPLIT_PATCH': True,
    # PATCH 메서드 필드 분리
    'ENUM_NAME_OVERRIDES': { # Enum 값 이름 최적화
        'ValidationErrorEnum': 'drf_spectacular.utils.ValidationError',
    },

    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "Bearer": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    'SECURITY': [{"Bearer": []}],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True, # 보안을 위해 리프레시 토큰 순환
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # JWT 전용 키로 분리 가능
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'colored': {
            '()': 'colorlog.ColoredFormatter',
            'format': '%(log_color)s[%(asctime)s] %(levelname)s [%(name)s:%(lineno)d] - %(message)s',
            'log_colors': {
                'DEBUG': 'cyan',
                'INFO': 'white',
                'WARNING': 'yellow',  
                'ERROR': 'red',       
                'CRITICAL': 'bold_red',
            },
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'colorlog.StreamHandler', # 일반 StreamHandler 대신 사용
            'formatter': 'colored',
        },
    },
    'loggers': {
        'backend': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# 1. Redis 연결 정보 
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '')
REDIS_HOST = os.getenv('REDIS_HOST', '') 
REDIS_PORT = os.getenv('REDIS_PORT', '')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 연결 유실 시 재시도 로직 
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
        }
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# 🌟 Celery 전용 설정 (DB 2)
CELERY_BROKER_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/2"
CELERY_RESULT_BACKEND = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/2"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'


_db_password = os.getenv("MYSQL_PASSWORD")
if not _db_password:
    _is_test_or_debug = ("test" in sys.argv or "pytest" in sys.modules or DEBUG)
    if _is_test_or_debug:
        _db_password = "1234"
    else:
        sys.exit("🔴 MYSQL_PASSWORD 환경변수가 설정되어 있지 않습니다. 서버를 시작할 수 없습니다.")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("MYSQL_DATABASE", ""),
        'USER': os.getenv("MYSQL_USER", ""),
        'PASSWORD': _db_password,
        'HOST': os.getenv("MYSQL_HOST", ""),
        'PORT': os.getenv("MYSQL_PORT", ""),
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 1. 소셜 플랫폼별 도메인 그룹화 
GOOGLE_DOMAINS = ["https://accounts.google.com", "https://apis.google.com", "https://*.googleusercontent.com"]
NAVER_DOMAINS = ["https://nid.naver.com", "https://ssl.pstatic.net"] # pstatic은 프로필 이미지용
# KAKAO_DOMAINS = ["https://kauth.kakao.com", "https://kapi.kakao.com", "https://*.kakaocdn.net"]

# 2. 통합 CSP 설정
CSP_DEFAULT_SRC = ("'self'",)

# 스크립트: 구글과 네이버의 인증 스크립트 허용
CSP_SCRIPT_SRC = ("'self'",) + tuple(GOOGLE_DOMAINS[:2]) + tuple(NAVER_DOMAINS[:1])

# 이미지: 소셜 서비스들의 프로필 이미지 서버 허용
CSP_IMG_SRC = ("'self'", "data:") + tuple(GOOGLE_DOMAINS[2:]) + tuple(NAVER_DOMAINS[1:])

# 프레임/연결: 인증 팝업 및 API 통신
CSP_FRAME_SRC = ("'self'", "https://accounts.google.com", "https://nid.naver.com")
CSP_CONNECT_SRC = ["'self'"] + list(GOOGLE_DOMAINS) + list(NAVER_DOMAINS)

# 스타일 및 폰트 (공통)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")

# 실제 차단은 하지 않고 콘솔에 에러 로그만 남깁니다.
CSP_REPORT_ONLY = True

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

if not DEBUG:
    SECURE_SSL_REDIRECT = True         # 모든 HTTP를 HTTPS로 리다이렉트
    SESSION_COOKIE_SECURE = True       # 쿠키를 HTTPS에서만 전송
    CSRF_COOKIE_SECURE = True          # CSRF 쿠키를 HTTPS에서만 전송
    SECURE_HSTS_SECONDS = 31536000     # 1년 동안 HTTPS 연결 강제 (HSTS)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Nginx가 X-Forwarded-Proto 헤더를 넘겨줄 때 인식함
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
# 업로드 이미지 저장 루트 (Docker: outgoing_volume → /usr/src/app/outgoing)
MEDIA_ROOT = os.path.join(BASE_DIR, 'outgoing')
MEDIA_URL = '/media/'
AUTH_USER_MODEL = 'user.User'

# --- YouTube → 레시피 자동 생성 (recipes.youtube_import) ---
# 유튜브 Data API 
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")
# OpenAI (필수). Chat Completions JSON mode.
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_YOUTUBE_IMPORT_MODEL = os.getenv("OPENAI_YOUTUBE_IMPORT_MODEL", "gpt-4o-mini")

# LLM provider switch: openai | gemini
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "gemini").strip().lower()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_YOUTUBE_IMPORT_MODEL = os.getenv("GEMINI_YOUTUBE_IMPORT_MODEL", "gemini-3-flash-preview")
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'DENY' # Clickjacking 방지
SECURE_CONTENT_TYPE_NOSNIFF = True # MIME 타입 스니핑 방지
SECURE_BROWSER_XSS_FILTER = True # 구형 브라우저 XSS 필터링