# Generated by Django 3.2.16 on 2026-03-20 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fridges.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('fridge_type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fridges', to='community.connectgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='식자재명')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('default_storage', models.CharField(choices=[('FRIDGE', '냉장'), ('FREEZER', '냉동'), ('ROOM_TEMP', '실온')], default='FRIDGE', max_length=20, verbose_name='기본 보관 방법')),
                ('default_expiry_days', models.PositiveIntegerField(default=7, help_text='기본 유통/소비기한(일). 등록 시 expiry_date 자동 계산에 사용.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='기본 소비기한(일)')),
                ('search_keywords', models.CharField(blank=True, help_text='예: 돼지고기, 겹살이, 포크 (쉼표로 구분)', max_length=255, verbose_name='검색 키워드')),
                ('default_unit', models.CharField(default='개', help_text='예: g, ml, 개, 단, 마리', max_length=20, verbose_name='기본 단위')),
                ('icon_url', models.URLField(blank=True, help_text='앱 화면에 보여줄 식자재 아이콘 이미지 주소', max_length=500, null=True, verbose_name='아이콘 URL')),
                ('icon_image', models.ImageField(blank=True, help_text='업로드한 식재료 아이콘 이미지 파일', null=True, upload_to=fridges.models._ingredient_icon_upload_to, verbose_name='아이콘 이미지')),
            ],
            options={
                'verbose_name': '표준 식자재',
                'verbose_name_plural': '표준 식자재 목록',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='수동 입력 또는 StandardIngredient.default_expiry_days 기준 자동 설정.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', '보유중'), ('CONSUMED', '소비됨'), ('EXPIRED', '만료'), ('DISCARDED', '폐기')], default='ACTIVE', max_length=20)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', to='fridges.fridge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
