# Generated by Django 3.2.16 on 2026-03-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fridges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fridges', to=settings.AUTH_USER_MODEL),
        ),
    ]
