# Generated by Django 3.2.16 on 2026-03-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapfolder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrap_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipescrap',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_scraps', to='community.scrapfolder'),
        ),
        migrations.AddField(
            model_name='recipescrap',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_scraps', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipescrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_scraps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingjournalcomment',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.cookingjournal'),
        ),
        migrations.AddField(
            model_name='cookingjournalcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_journal_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingjournal',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_journals', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='cookingjournal',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='visibility=SPECIFIC_GROUPS일 때 공개할 그룹들.', related_name='cooking_journals_visible', to='community.ConnectGroup'),
        ),
        migrations.AddField(
            model_name='cookingjournal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectgroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_group_members', to='community.connectgroup'),
        ),
        migrations.AddField(
            model_name='connectgroupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='scrapfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_group_default', True)), fields=('group',), name='uniq_group_default_scrap_folder_per_group'),
        ),
        migrations.AlterUniqueTogether(
            name='recipescrap',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='connectgroupmember',
            unique_together={('group', 'user')},
        ),
    ]
