# Generated by Django 3.2.16 on 2026-03-20 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipescrap',
            unique_together={('user', 'folder', 'recipe')},
        ),
    ]
