# Generated by Django 3.2.16 on 2026-03-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeviewlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_view_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipetagrelation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tag_relations', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipetagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_tag_relations', to='recipes.recipetag'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipereport',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipecategoryrelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category_relations', to='recipes.recipecategory'),
        ),
        migrations.AddField(
            model_name='recipecategoryrelation',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category_relations', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipeviewlog',
            index=models.Index(fields=['recipe', 'created_at'], name='recipes_rec_recipe__840175_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeviewlog',
            index=models.Index(fields=['user', 'recipe', 'created_at'], name='recipes_rec_user_id_3fd6a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipetagrelation',
            unique_together={('recipe', 'tag')},
        ),
        migrations.AddIndex(
            model_name='recipereport',
            index=models.Index(fields=['recipe'], name='recipes_rec_recipe__a7b4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='recipereport',
            index=models.Index(fields=['reporter'], name='recipes_rec_reporte_ca350e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipecategoryrelation',
            unique_together={('recipe', 'category')},
        ),
    ]
